1095 - Move useful ElementDefinition ext methods to a single place.
FirelyTeam/firely-net-sdk pull request #1934
Opened 2022-01-04 13:32 UTC by ewoutkramer

Collected useful ElementDefinition extension methods to a single ElementDefinitionExtensions class in the model assembly.

2022-01-19 14:58 UTC, marcovisserFurore requested changes
I think file TypeRefExtensions.cs can be removed as well, right?

2022-01-19 14:58 UTC, marcovisserFurore commented on src/Hl7.Fhir.Specification/Validation/TypeRefExtensions.cs
>  namespace Hl7.Fhir.Validation
Should this file not removed then?

2022-01-20 09:51 UTC, marcovisserFurore approved these changes

2022-01-20 09:55 UTC, mmsmits approved these changes

2022-01-20 10:27 UTC, merged