Add roundtrip tests for new serializers [R4]
FirelyTeam/firely-net-sdk pull request #2276
Opened 2022-10-24 11:51 UTC by mmsmits

2022-10-26 13:37 UTC, marcovisserFurore requested changes
Well done! Looks nice and much more clearer.

Some small things to think about.

2022-10-26 13:37 UTC, marcovisserFurore commented on src/Hl7.Fhir.Serialization.Tests/RoundtripNewSerializers.cs
> +            var baseTestPath = Path.Combine(Path.GetTempPath(), xmlTestFolder);
Can this be done in the method `prepareExampleZipFiles`? Then it is done only once, instead for every file.

2022-10-26 13:37 UTC, marcovisserFurore commented on src/Hl7.Fhir.Serialization.Tests/RoundtripNewSerializers.cs
> +            var baseTestPath = Path.Combine(Path.GetTempPath(), jsonTestFolder);
Can this be done in the method `prepareExampleZipFiles`? Then it is done only once, instead for every file.

2022-12-23 09:58 UTC, mmsmits commented
Replaced with this PR: https://github.com/FirelyTeam/firely-net-sdk/pull/2347

2022-12-23 09:58 UTC, closed without merging