Allign CanonicalUri classes
FirelyTeam/firely-net-sdk pull request #2358
Opened 2023-01-06 13:45 UTC by mmsmits

fixes #2268

2023-01-10 13:15 UTC, ewoutkramer requested changes

2023-01-10 15:25 UTC, ewoutkramer approved these changes

2023-01-10 15:25 UTC, merged

2023-01-11 04:04 UTC, brianpos commented
@ewoutkramer   Wondering why this isn't in https://github.com/FirelyTeam/firely-net-common/blob/develop/src/Hl7.Fhir.Support.Poco/Model/Canonical.cs where it isn't version specific?

2023-01-11 09:09 UTC, ewoutkramer commented
> @ewoutkramer Wondering why this isn't in https://github.com/FirelyTeam/firely-net-common/blob/develop/src/Hl7.Fhir.Support.Poco/Model/Canonical.cs where it isn't version specific?

In SDK 5.0, the common repo has been integrated with the main one. So, this is actually the same Canonical you made your PR on!