Support pluggable serialization for FhirClient (Requests)
FirelyTeam/firely-net-sdk pull request #2402
Opened 2023-03-07 16:28 UTC by ewoutkramer

This PR adds support for pluggable serialization to the FhirClient. To make the work (and PR review) manageable, this PR only implements this for the sending side.

* It does include all the serialization infrastructure and changes to FhirClientSettings to make this possible.
* The whole sending (requesting) side of the client has been refreshed and updated.
* All unit tests for the requesting side now work on HttpRequestMessage, so we are testing directly the outgoing message (no mocking necessary)

The conversion of the Bundle.EntryComponent is now done using extension methods on HttpRequestMessage - these are independent of the FhirClient and could easily be used by others to help creating requests not supported by the FhirClient.

2023-03-15 10:54 UTC, marcovisserFurore requested changes
See my comments

2023-03-16 11:02 UTC, marcovisserFurore commented
This PR resolves #2409

2023-03-21 16:45 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/CompressedContent.cs
> +            return _wrapped
Yes!

2023-03-21 16:51 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/CompressedContent.cs
> +            return _wrapped
I am not awaiting anything, just returning a Task - I actually tried to add `ConfigureAwait`, but that does no longer return a Task, but another "awaitable" thing, so this is really only sensible when you call await!

2023-03-21 16:52 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Serialization/engine/PocoSerializationEngine.cs
> +        public virtual Resource? DeserializeFromXml(string data) => new BaseFhirXmlPocoDeserializer(_inspector).DeserializeResource(data);
I have no clue.

2023-03-21 16:53 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/TransactionBuilder.cs
> +            var entry = TransactionBuilder.newEntry(Bundle.HTTPVerb.PUT, InteractionType.Update);
I don't understand it myself - I am still doing SDK work in VS, so that cannot be it. I was myself slightly confused why this happened.

2023-03-21 17:00 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/HttpClientRequester.cs
> +//        public async Task<EntryResponse> ExecuteAsync(HttpRequestMessage message, IFhirSerializationEngine ser, string? mediaTypeFhirVersion, CancellationToken ct)
It's actually new, I was piloting something. I decided to keep it, but I don't know why anymore, so I'll just throw it away hahaha.

2023-03-21 17:04 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/FhirClientSettings.cs
>              other.ParserSettings = ParserSettings;
ai.

2023-03-21 17:07 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/HttpContentBuilders.cs
> +        internal static HttpContent CreateContentFromBinary(Binary b)
Yes, indeed. I always either do internal methods in public classes or public methods inside internal classes, but not both - I agree with Eric Lippert.

2023-03-21 17:08 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/HttpContentBuilders.cs
> +        internal static HttpContent CreateContentFromBinary(Binary b)
> Basically, my attitude is: suppose I decided to make this internal class into a public class. In order to do that, I want to change exactly one thing: the accessibility of the class. If turning an internal class into a public class means that I have to also turn an internal member into a public member, then that member was part of the public surface area of the class, and it should have been public in the first place.

Yes!

2023-03-21 17:09 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/HttpContentBuilders.cs
> +        internal static HttpContent CreateContentFromBinary(Binary b)
This class *will* be public at some future moment, so then these methods will need to be public too.

2023-03-21 17:16 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Utility/ReflectionHelper.cs
> +            var versionInfo = a.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
The methods in ReflectionHelper themselves do not cache (that's not their responsibility), but they often used by the ModelInspector (which does cache). Similarly, I think in this case the FhirClient could cache it.  It's really not that relevant compared to the amount of I/O a FhirClient is doing, but it was easy to turn it into a `static readonly` "constant", so I did that anyway.

2023-03-30 07:59 UTC, marcovisserFurore approved these changes

2023-03-30 08:15 UTC, merged