2555 Add support for multiple valuesets and system filters to ValueSetExpander
FirelyTeam/firely-net-sdk pull request #2558
Opened 2023-08-02 06:05 UTC by ewoutkramer

Expander now supports having more than one valueset in an include and specifying a valueset + system to limit the import of said valuesets.

Also reworked the expander to more closely follow the expansion algorithm specified in the spec.

- Using more delayed processing, so processing valuesets that are too big is actually stopped before attempting it.
- Documented all steps more clearly, referring to the spec.
- specifying both System and ValueSet will now do an intersection.

2023-08-02 14:56 UTC, ewoutkramer commented
Note: this PR only contains the changes for STU3, for ease of review.

PR #2559 will make sure this functionality also exists for R4+, but doing that in this PR would make reviewing hard due to reorganizations in the directory structure.

TL;DR:  first review this PR, then 2559 and if both are ok, merge this one first, then 2559.

2023-08-02 15:11 UTC, ewoutkramer commented on src/Hl7.Fhir.Shims.STU3AndUp/Specification/Terminology/ValueSetExpander.cs
> +﻿#nullable enable
This is a dead file, it is not part of the project and is not compiled. No review necessary (it's a copy of the other ValueSetExpander.cs anywat).

2023-08-03 13:27 UTC, mmsmits requested changes

2023-08-03 13:27 UTC, mmsmits commented on src/Hl7.Fhir.STU3/Specification/Terminology/ValueSetExpander.cs
> +                addCapped(result, concepts, $"Import of valuesets '{string.Join(",", conceptSet.ValueSet)}' would result in an expqansion larger than the maximum expansion size.");
```suggestion
                addCapped(result, concepts, $"Import of valuesets '{string.Join(",", conceptSet.ValueSet)}' would result in an expansion larger than the maximum expansion size.");
```

2023-08-03 14:40 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Specification/Terminology/ValueSetExpanderSettings.cs
> +            // other.IncludeInactive = IncludeInactive;
We probably have to. But it was too much yak-shaving at this point in time, so I changed my mind and let it be.

2023-08-03 14:42 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Specification/Terminology/ValueSetExpanderSettings.cs
> +            // other.IncludeInactive = IncludeInactive;
Actually, it's too hard to impelement at this time, or anytime soon, so I'll remove it.

2023-08-03 14:48 UTC, ewoutkramer commented on src/Hl7.Fhir.STU3/Specification/Terminology/ValueSetExpander.cs
> +                throw Error.InvalidOperation($"Encountered a ConceptSet with neither a 'system' nor a 'valueset'");
It's not an error. According to http://hl7.org/fhir/valueset.html#combinations, a valueset may have both a compose, expand, one of the two, or none ;-)

I'll document that there.

2023-08-03 14:51 UTC, mmsmits commented on src/Hl7.Fhir.STU3/Specification/Terminology/ValueSetExpander.cs
> +                throw Error.InvalidOperation($"Encountered a ConceptSet with neither a 'system' nor a 'valueset'");
I actually meant the vsd-1, we can enforce it with an error (like you do), but we can also just return without throwing an exception (act stupid). 
What would a user expect?

2023-08-03 14:53 UTC, ewoutkramer commented on src/Hl7.Fhir.STU3/Specification/Terminology/ValueSetExpander.cs
> +                throw Error.InvalidOperation($"Encountered a ConceptSet with neither a 'system' nor a 'valueset'");
This is existing behaviour, so I think we should let it in.

2023-08-03 14:54 UTC, ewoutkramer commented on src/Hl7.Fhir.STU3/Specification/Terminology/ValueSetExpander.cs
> +                throw Error.InvalidOperation($"Encountered a ConceptSet with neither a 'system' nor a 'valueset'");
(in the old code the enforcement of this rule was spread over multiple lines, but I reshuffled it so it becomes really explicit)

2023-08-03 14:59 UTC, mmsmits approved these changes

2023-08-03 14:59 UTC, merged