Improved binary support
FirelyTeam/firely-net-sdk pull request #2771
Opened 2024-04-11 15:12 UTC by Kasdejong

## Description
Added improved binary support for the FhirClient. 

- The FhirClient will attempt to request/recieve binary data instead of "Binary" resources where possible (these will still be parsed into resources upon receiving them, but it puts less stress on the network). If the server sends a resource nonetheless, the old implementation will handle this. This can be switched off in the settings (is on by default). 

- It is now also possible to send binary data, but far from all servers support this, so this will have to be turned on manually.

## Related issues
Closes #2695 

## Testing
Integration test against firely and HAPI

2024-04-16 12:29 UTC, ewoutkramer requested changes

2024-04-16 12:29 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/EntryToHttpExtensions.cs
> +            bool binaryEndpoint = true)
Since the binary endpoint is the exception, shoud the default not be `false`?

2024-04-16 12:29 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/FhirClientSettings.cs
> +        /// How to transfer binary data when receiving data from a Binary endpoint.
Maybe change the comment to: "Whether we ask the server to return us binary data or a Binary resource."

2024-04-16 12:29 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/FhirClientSettings.cs
> +        /// How to transfer binary data when receiving data from a Binary endpoint.
Maybe it should be called "BinaryReceivePreference"

2024-04-16 12:29 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Rest/HttpContentParsers.cs
> +            var isResource = ContentType.GetResourceFormatFromContentType(message.Content.GetContentType()) != ResourceFormat.Unknown;
Maybe `isResource` should be `usesFhirFormat`.

2024-04-16 12:29 UTC, ewoutkramer commented on src/Hl7.Fhir.Shared.Tests/Rest/FhirClientTests.cs
> +        [TestCategory("IntegrationTest"), TestCategory("FhirClient")]
Did you test the normal behaviour - have you run some of the other Fhirclient tests to see whether we had regressions?

2024-04-23 07:39 UTC, ewoutkramer approved these changes

2024-04-23 07:39 UTC, merged

2024-05-01 13:14 UTC, mmsmits commented
also closes #1340