fix: #2802 - let SnapshotSource reuse self-generated snapshot
FirelyTeam/firely-net-sdk pull request #2803
Opened 2024-06-25 10:22 UTC by cknaap

## Description
If SnapshotSource detects a snapshot generated by our own SnapshotGenerator, it does not re-generate it.

## Related issues
Fixes #2802.

## Testing
See 2 new unit tests in the PR.

## FirelyTeam Checklist
- [ ] **Update the title** of the PR to be succinct and less than 50 characters
- [ ] Mark the PR with the label **breaking change** when this PR introduces breaking changes

2024-06-25 11:42 UTC, ewoutkramer commented
I do not understand why #2802 is considered a bug. When you set the setting "ForceRegenerateSnapshots" to true, it will re-generate the snapshots, no matter what. This is the documented behaviour of this option:

>  Force expansion of all external profiles, disregarding any existing snapshot components.
     If enabled, the snapshot generator will re-generate the snapshot components of all the core resource and datatype profiles
     as well as of all other referenced external profiles.
     Re-generated snapshots are annotated to prevent duplicate re-generation (assuming the provided resource resolver uses caching).
     If disabled (default), then the snapshot generator relies on existing snapshot components, if they exist.

This PR does not look like a fix, but a behavioural change. The "ForceRegenerateSnapshot" used to *always* regenerate the snapshot, now it will only renegerate it if it was not created by us. That's a breaking change that we should not make in a non-major version.  

Why don't you just set ForceRegenerateSnapshot to `false` instead? This will create a new snapshot if there is none, or if the snapshot is not ours.

2024-06-26 08:57 UTC, ewoutkramer commented
Design discussion will be continued on issue #2802.

2024-08-15 07:11 UTC, Kasdejong approved these changes, later dismissed
I think this PR is overall an improvement now. From what I've read this is what we're going with, so I'll pull it

2024-08-15 07:14 UTC, Kasdejong commented
I will also deprecate the setting for good measure, because it seems as though right now it does not do anything. In fact, setting it to false while there is no snapshot will just produce no snapshot now :)

2024-08-19 14:12 UTC, mmsmits requested changes

2024-08-19 14:12 UTC, mmsmits commented on src/Hl7.Fhir.Shims.Base/Specification/Source/SnapshotSource.cs
> +                if (!sd.HasSnapshot || (Generator.Settings.ForceRegenerateSnapshots && !sd.Snapshot.IsCreatedBySnapshotGenerator()))
As Ewout says in https://github.com/FirelyTeam/firely-net-sdk/issues/2802 this will surely result in regressions. We shouldn't change this.

2024-09-04 13:52 UTC, mmsmits commented
This still needs to be done:

>We should obsolete it and **introduce a more explicit setting. Basically there are only two cases:**

    Add a snapshot if there is none or use whatever is there (new behaviour)
    Regenerate snapshot once to ensure it is "ours" (and/or at least updated to the lastest version) (current default behaviour)

2024-09-10 13:11 UTC, mmsmits approved these changes

2024-09-10 13:11 UTC, merged