Base POCO parsers/serializers on POCO, not IROD
FirelyTeam/firely-net-sdk pull request #2950
Opened 2024-10-23 16:54 UTC by ewoutkramer

Fixes #2917.

2024-10-23 17:07 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Serialization/BaseFhirJsonPocoSerializer.cs
> +    public string SerializeToString(Resource element)
Should be `Base` too to be consistent.

2024-10-24 09:19 UTC, ewoutkramer commented on src/Hl7.Fhir.Base/Serialization/BaseFhirJsonPocoSerializer.cs
> +    public string SerializeToString(Resource element)
Done.

2024-10-24 11:57 UTC, Kasdejong commented on src/Hl7.Fhir.Base/Serialization/FhirXmlBuilderExtensions.cs
> +            // Note that this code is temporary, as we the above code will be re-instated here. It's therefore
if it is temporary, maybe we should mark it with [TemporarilyChanged]?

2024-10-24 11:57 UTC, Kasdejong commented on src/Hl7.Fhir.Base/Serialization/FhirXmlBuilderExtensions.cs
> +            // Note that this code is temporary, as we the above code will be re-instated here. It's therefore
if it is temporary, maybe we should mark it with [TemporarilyChanged]?

2024-10-24 11:58 UTC, Kasdejong requested changes
I accidentally set the review to "comment" instead of "request changes", this should tag it appropriately

2024-11-13 14:05 UTC, Kasdejong approved these changes

2024-11-13 14:54 UTC, merged